In [1]:
import fxcmpy
import pandas as pd
import numpy as np
import datetime as dt

#IMPORTING Hull Moving Average from pyti
from pyti.hull_moving_average import hull_moving_average as hma

# Allows for printing the whole data frame
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
#set connection
con = fxcmpy.fxcmpy(config_file='fxcm.cfg')

#get candle data 2016-01-01 to 2018-06-19
df = con.get_candles('US30', period='m5',start= dt.datetime(2018, 9, 1),end = dt.datetime(2018, 10, 1))

#check connection
con.is_connected()

True

In [3]:
#look into data
df.tail()

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty
date,,,,,,,,,
2018-09-30 23:40:00,26592.75,26588.70,26593.1,26587.05,26595.00,26590.60,26595.2,26589.20,474
2018-09-30 23:45:00,26588.70,26585.00,26590.7,26578.95,26590.60,26587.35,26592.9,26581.35,612
2018-09-30 23:50:00,26585.00,26581.05,26585.7,26580.20,26587.35,26583.60,26588.5,26582.70,647
2018-09-30 23:55:00,26581.05,26589.80,26590.7,26580.75,26583.60,26591.85,26592.7,26582.70,467
2018-10-01 00:00:00,26589.80,26579.10,26589.9,26577.45,26591.85,26581.05,26592.7,26580.00,1108

In [4]:
# Define pip cost and lot size
pip_cost = .0911
lot_size = 10

# Define EMA Fast / Slow parameters
fast = 9
slow = 18

# HMA fast and slow calculation
df['hma_fast'] = hma(df['bidclose'], fast)
df['hma_slow'] = hma(df['bidclose'], slow)

# Entry signals when HMA(fast) corsses above the HMA(slow). Sell signals when HMA(fast) crossed below the HMA(slow).
df['signal'] = np.where(df['hma_fast'] < df['hma_slow'], 1, 0)
df['position'] = df['signal'].diff()

In [5]:
df[1:50]

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,hma_fast,hma_slow,signal,position
date,,,,,,,,,,,,,
2018-09-02 22:05:00,26005.00,25999.80,26005.10,25995.7,26007.00,26001.70,26010.20,25998.90,263,NaN,NaN,0,0.0
2018-09-02 22:10:00,25999.80,25997.70,26002.05,25993.8,26001.70,26000.55,26005.60,25995.50,230,NaN,NaN,0,0.0
2018-09-02 22:15:00,25997.70,25996.20,25999.35,25993.4,26000.55,26001.10,26003.55,25998.30,155,NaN,NaN,0,0.0
2018-09-02 22:20:00,25996.20,25999.20,26001.75,25993.4,26001.10,26002.40,26005.50,25999.60,79,NaN,NaN,0,0.0
2018-09-02 22:25:00,25999.20,25999.95,26000.30,25995.1,26002.40,26002.80,26004.90,26001.15,120,NaN,NaN,0,0.0
2018-09-02 22:30:00,25999.95,25994.60,25999.95,25994.4,26002.80,26001.15,26002.65,25999.80,64,NaN,NaN,0,0.0
2018-09-02 22:35:00,25994.60,25992.40,25995.30,25992.4,26001.15,25995.80,26002.05,25995.80,55,NaN,NaN,0,0.0
2018-09-02 22:40:00,25992.40,25994.90,26000.00,25992.8,25995.80,25999.05,26003.70,25994.50,138,NaN,NaN,0,0.0
2018-09-02 22:45:00,25994.90,25997.90,25999.40,25994.4,25999.05,26002.20,26004.30,25998.90,111,NaN,NaN,0,0.0
2018-09-02 22:50:00,25997.90,25991.80,26000.00,25986.8,26002.20,25995.90,26004.30,25990.50,149,25993.741667,NaN,0,0.0
2018-09-02 22:55:00,25991.80,25989.00,25991.80,25987.1,25995.90,25993.50,25995.60,25992.00,84,25992.172963,NaN,0,0.0
2018-09-02 23:00:00,25989.00,25985.80,25991.10,25985.8,25993.50,25990.05,25996.50,25990.05,141,25988.887037,NaN,0,0.0
2018-09-02 23:05:00,25985.80,25982.80,25985.80,25977.5,25990.05,25988.10,25990.05,25982.70,160,25984.801481,NaN,0,0.0
2018-09-02 23:10:00,25982.80,25984.80,25986.60,25981.5,25988.10,25986.60,25990.50,25984.60,65,25982.334444,NaN,0,0.0
2018-09-02 23:15:00,25984.80,25990.50,25990.50,25982.5,25986.60,25992.50,25993.95,25986.60,75,25983.359074,NaN,0,0.0
2018-09-02 23:20:00,25990.50,25991.50,25992.70,25989.5,25992.50,25994.30,25996.20,25992.60,83,25986.625185,NaN,0,0.0
2018-09-02 23:25:00,25991.50,25991.80,25992.50,25987.8,25994.30,25994.40,25995.90,25992.60,125,25990.218148,NaN,0,0.0
2018-09-02 23:30:00,25991.80,25996.35,25999.80,25989.8,25994.40,25998.90,26002.05,25993.40,210,25993.949815,NaN,0,0.0
2018-09-02 23:35:00,25996.35,25999.05,26002.80,25996.2,25998.90,26000.30,26005.65,25998.60,431,25997.442963,NaN,0,0.0
2018-09-02 23:40:00,25999.05,25995.75,25998.00,25992.5,26000.30,25998.45,26000.30,25995.20,166,25999.073704,25992.117444,0,0.0
2018-09-02 23:45:00,25995.75,26000.70,26001.90,25994.6,25998.45,26003.40,26004.75,25997.40,144,26000.542407,25994.837398,0,0.0
2018-09-02 23:50:00,26000.70,25999.40,26002.80,25993.4,26003.40,26003.20,26005.95,25998.50,172,26001.065185,25997.315550,0,0.0
2018-09-02 23:55:00,25999.40,25996.70,26001.80,25995.6,26003.20,25999.50,26005.05,25999.50,134,26000.292778,25998.974608,0,0.0
2018-09-03 00:00:00,25996.70,25986.80,25997.40,25981.8,25999.50,25988.80,26001.15,25983.90,359,25995.925741,25998.698573,1,1.0
2018-09-03 00:05:00,25986.80,25984.80,25989.00,25983.1,25988.80,25987.60,25992.45,25985.80,322,25989.767222,25996.786158,1,0.0
2018-09-03 00:10:00,25984.80,25988.20,25988.20,25978.9,25987.60,25991.00,25991.40,25981.40,259,25985.445926,25994.388327,1,0.0
2018-09-03 00:15:00,25988.20,25988.10,25992.10,25983.3,25991.00,25990.20,25995.30,25986.00,305,25983.949630,25991.962959,1,0.0
2018-09-03 00:20:00,25988.10,25989.10,25993.30,25986.1,25990.20,25991.90,25996.05,25988.10,225,25985.066852,25990.010655,1,0.0
2018-09-03 00:25:00,25989.10,25991.20,25992.40,25989.2,25991.90,25993.20,25995.75,25991.20,127,25987.535741,25988.801544,1,0.0
2018-09-03 00:30:00,25991.20,25990.10,25992.30,25987.3,25993.20,25992.10,25995.45,25990.00,156,25989.533148,25987.992351,0,-1.0
2018-09-03 00:35:00,25990.10,25983.10,25990.10,25980.4,25992.10,25984.90,25993.00,25983.15,233,25988.538889,25986.793146,0,0.0
2018-09-03 00:40:00,25983.10,25981.90,25983.10,25969.9,25984.90,25984.60,25985.80,25974.45,378,25985.558148,25985.355591,0,0.0
2018-09-03 00:45:00,25981.90,25985.80,25987.80,25981.2,25984.60,25987.90,25990.80,25983.80,257,25983.472963,25984.421614,1,1.0
2018-09-03 00:50:00,25985.80,25979.80,25986.00,25978.1,25987.90,25981.90,25988.90,25981.40,162,25981.253333,25983.241953,1,0.0
2018-09-03 00:55:00,25979.80,25988.10,25988.10,25975.8,25981.90,25990.20,25990.30,25978.95,217,25982.225926,25982.972211,1,0.0
2018-09-03 01:00:00,25988.10,25983.30,25989.10,25983.3,25990.20,25986.20,25991.40,25986.00,318,25983.143333,25982.738468,0,-1.0
2018-09-03 01:05:00,25983.30,25981.10,25985.10,25980.1,25986.20,25983.90,25988.00,25982.70,174,25983.068148,25982.215462,0,0.0
2018-09-03 01:10:00,25981.10,25973.40,25985.10,25973.4,25983.90,25977.15,25987.95,25977.00,349,25979.848148,25980.705105,1,1.0
2018-09-03 01:15:00,25973.40,25974.50,25977.20,25964.5,25977.15,25979.10,25981.50,25968.90,835,25975.830000,25978.737456,1,0.0
2018-09-03 01:20:00,25974.50,25979.55,25981.95,25971.5,25979.10,25981.70,25984.80,25975.80,589,25974.385370,25977.421690,1,0.0
2018-09-03 01:25:00,25979.55,25980.40,25982.10,25974.2,25981.70,25983.10,25985.70,25978.65,443,25975.589815,25976.826409,1,0.0
2018-09-03 01:30:00,25980.40,25987.10,25988.30,25971.3,25983.10,25989.10,25992.90,25975.50,1479,25980.151852,25977.601398,0,-1.0
2018-09-03 01:35:00,25987.10,25983.10,25987.10,25980.3,25989.10,25985.20,25990.50,25982.70,686,25983.730741,25978.727520,0,0.0
2018-09-03 01:40:00,25983.10,25985.20,25986.40,25982.1,25985.20,25987.20,25990.05,25984.00,387,25986.100370,25980.086526,0,0.0
2018-09-03 01:45:00,25985.20,25988.20,25992.10,25982.2,25987.20,25990.20,25995.30,25984.20,478,25987.792037,25981.930070,0,0.0
2018-09-03 01:50:00,25988.20,25985.30,25988.20,25982.2,25990.20,25988.00,25991.25,25984.20,474,25988.025556,25983.612480,0,0.0
2018-09-03 01:55:00,25985.30,25986.40,25996.10,25984.3,25988.00,25988.90,25999.05,25987.90,647,25987.852963,25985.264784,0,0.0
2018-09-03 02:00:00,25986.40,25977.80,25986.40,25975.8,25988.90,25980.90,25989.90,25979.85,438,25984.754074,25985.580620,1,1.0
2018-09-03 02:05:00,25977.80,25971.00,25977.10,25970.0,25980.90,25976.40,25981.35,25974.45,679,25978.733704,25983.981029,1,0.0

In [6]:
begin_prices = []
end_prices = []
profits = 0

# get open/close price for each open position
for i, row in df.iterrows():
    if row['position'] == 1:
        begin_prices.append(float(row['bidopen']))
    if row['position'] == -1:
        end_prices.append(float(row['bidopen']))

# Calculating the profit / loss
for i in range(len(begin_prices)):
    profit = (begin_prices[i] - end_prices[i]) * pip_cost * lot_size
    profits += profit
    print("The return for trade " + str(i + 1) + " is: " + str(int(profit)))
    
print("The return for the period is: " + str(int(profits)))

The return for trade 1 is: 5
The return for trade 2 is: -5
The return for trade 3 is: 0
The return for trade 4 is: 15
The return for trade 5 is: 14
The return for trade 6 is: -2
The return for trade 7 is: 0
The return for trade 8 is: -7
The return for trade 9 is: -2
The return for trade 10 is: -8
The return for trade 11 is: -4
The return for trade 12 is: 2
The return for trade 13 is: -8
The return for trade 14 is: 28
The return for trade 15 is: 13
The return for trade 16 is: -1
The return for trade 17 is: 0
The return for trade 18 is: 2
The return for trade 19 is: 0
The return for trade 20 is: -4
The return for trade 21 is: 3
The return for trade 22 is: 34
The return for trade 23 is: -2
The return for trade 24 is: 3
The return for trade 25 is: 8
The return for trade 26 is: -14
The return for trade 27 is: -2
The return for trade 28 is: 37
The return for trade 29 is: 33
The return for trade 30 is: 64
The return for trade 31 is: -3
The return for trade 32 is: 16
The return for trade 33 is: -28
The return for trade 34 is: 65
The return for trade 35 is: -22
The return for trade 36 is: 5
The return for trade 37 is: 2
The return for trade 38 is: 4
The return for trade 39 is: -1
The return for trade 40 is: 9
The return for trade 41 is: 4
The return for trade 42 is: 15
The return for trade 43 is: 9
The return for trade 44 is: 42
The return for trade 45 is: 26
The return for trade 46 is: -18
The return for trade 47 is: 9
The return for trade 48 is: 2
The return for trade 49 is: 15
The return for trade 50 is: 29
The return for trade 51 is: 15
The return for trade 52 is: -18
The return for trade 53 is: -4
The return for trade 54 is: 9
The return for trade 55 is: 1
The return for trade 56 is: -22
The return for trade 57 is: 9
The return for trade 58 is: 4
The return for trade 59 is: 1
The return for trade 60 is: 0
The return for trade 61 is: -7
The return for trade 62 is: -8
The return for trade 63 is: 21
The return for trade 64 is: 24
The return for trade 65 is: 3
The return for trade 66 is: 2
The return for trade 67 is: -25
The return for trade 68 is: -15
The return for trade 69 is: 42
The return for trade 70 is: 6
The return for trade 71 is: -4
The return for trade 72 is: 129
The return for trade 73 is: 17
The return for trade 74 is: -21
The return for trade 75 is: -22
The return for trade 76 is: -21
The return for trade 77 is: 33
The return for trade 78 is: 1
The return for trade 79 is: 5
The return for trade 80 is: 44
The return for trade 81 is: 16
The return for trade 82 is: 6
The return for trade 83 is: 1
The return for trade 84 is: -6
The return for trade 85 is: 20
The return for trade 86 is: 13
The return for trade 87 is: 0
The return for trade 88 is: 2
The return for trade 89 is: 17
The return for trade 90 is: 57
The return for trade 91 is: -30
The return for trade 92 is: -7
The return for trade 93 is: 129
The return for trade 94 is: -20
The return for trade 95 is: -6
The return for trade 96 is: 16
The return for trade 97 is: 0
The return for trade 98 is: -11
The return for trade 99 is: -8
The return for trade 100 is: -9
The return for trade 101 is: 7
The return for trade 102 is: -3
The return for trade 103 is: 5
The return for trade 104 is: 6
The return for trade 105 is: -1
The return for trade 106 is: -4
The return for trade 107 is: 2
The return for trade 108 is: -15
The return for trade 109 is: 1
The return for trade 110 is: 0
The return for trade 111 is: 6
The return for trade 112 is: 65
The return for trade 113 is: -7
The return for trade 114 is: 19
The return for trade 115 is: 0
The return for trade 116 is: 2
The return for trade 117 is: -5
The return for trade 118 is: 24
The return for trade 119 is: 2
The return for trade 120 is: 2
The return for trade 121 is: 1
The return for trade 122 is: 1
The return for trade 123 is: 0
The return for trade 124 is: 4
The return for trade 125 is: -1
The return for trade 126 is: 0
The return for trade 127 is: 25
The return for trade 128 is: 70
The return for trade 129 is: -6
The return for trade 130 is: 23
The return for trade 131 is: -12
The return for trade 132 is: 6
The return for trade 133 is: -8
The return for trade 134 is: 13
The return for trade 135 is: -15
The return for trade 136 is: -11
The return for trade 137 is: 10
The return for trade 138 is: 11
The return for trade 139 is: 0
The return for trade 140 is: -13
The return for trade 141 is: -1
The return for trade 142 is: 28
The return for trade 143 is: 16
The return for trade 144 is: -1
The return for trade 145 is: 3
The return for trade 146 is: -5
The return for trade 147 is: -9
The return for trade 148 is: 6
The return for trade 149 is: 29
The return for trade 150 is: 0
The return for trade 151 is: 23
The return for trade 152 is: -9
The return for trade 153 is: 6
The return for trade 154 is: 55
The return for trade 155 is: 103
The return for trade 156 is: 25
The return for trade 157 is: 8
The return for trade 158 is: -2
The return for trade 159 is: -6
The return for trade 160 is: 20
The return for trade 161 is: 20
The return for trade 162 is: -1
The return for trade 163 is: 2
The return for trade 164 is: 8
The return for trade 165 is: -10
The return for trade 166 is: 0
The return for trade 167 is: -3
The return for trade 168 is: -18
The return for trade 169 is: 86
The return for trade 170 is: 12
The return for trade 171 is: -4
The return for trade 172 is: 5
The return for trade 173 is: 0
The return for trade 174 is: -3
The return for trade 175 is: -8
The return for trade 176 is: -1
The return for trade 177 is: 17
The return for trade 178 is: 6
The return for trade 179 is: -7
The return for trade 180 is: 3
The return for trade 181 is: -15
The return for trade 182 is: 6
The return for trade 183 is: -6
The return for trade 184 is: 12
The return for trade 185 is: -6
The return for trade 186 is: 13
The return for trade 187 is: 25
The return for trade 188 is: 92
The return for trade 189 is: -14
The return for trade 190 is: -9
The return for trade 191 is: 51
The return for trade 192 is: 7
The return for trade 193 is: -7
The return for trade 194 is: 16
The return for trade 195 is: 3
The return for trade 196 is: 0
The return for trade 197 is: 6
The return for trade 198 is: 8
The return for trade 199 is: -1
The return for trade 200 is: 23
The return for trade 201 is: -3
The return for trade 202 is: 10
The return for trade 203 is: -1
The return for trade 204 is: 22
The return for trade 205 is: 3
The return for trade 206 is: 51
The return for trade 207 is: 65
The return for trade 208 is: -7
The return for trade 209 is: 78
The return for trade 210 is: 0
The return for trade 211 is: 1
The return for trade 212 is: 6
The return for trade 213 is: -6
The return for trade 214 is: -2
The return for trade 215 is: 6
The return for trade 216 is: 2
The return for trade 217 is: -6
The return for trade 218 is: -8
The return for trade 219 is: 4
The return for trade 220 is: -7
The return for trade 221 is: -9
The return for trade 222 is: 48
The return for trade 223 is: -14
The return for trade 224 is: 0
The return for trade 225 is: -18
The return for trade 226 is: -7
The return for trade 227 is: -7
The return for trade 228 is: 16
The return for trade 229 is: 15
The return for trade 230 is: -8
The return for trade 231 is: 23
The return for trade 232 is: 7
The return for trade 233 is: -11
The return for trade 234 is: 13
The return for trade 235 is: 0
The return for trade 236 is: 1
The return for trade 237 is: 1
The return for trade 238 is: -5
The return for trade 239 is: 3
The return for trade 240 is: 0
The return for trade 241 is: 15
The return for trade 242 is: 7
The return for trade 243 is: -9
The return for trade 244 is: -4
The return for trade 245 is: -1
The return for trade 246 is: -4
The return for trade 247 is: -7
The return for trade 248 is: 26
The return for trade 249 is: -13
The return for trade 250 is: -4
The return for trade 251 is: 8
The return for trade 252 is: -3
The return for trade 253 is: 0
The return for trade 254 is: 8
The return for trade 255 is: -1
The return for trade 256 is: 5
The return for trade 257 is: -1
The return for trade 258 is: 0
The return for trade 259 is: 4
The return for trade 260 is: 6
The return for trade 261 is: -5
The return for trade 262 is: -18
The return for trade 263 is: -7
The return for trade 264 is: -13
The return for trade 265 is: -12
The return for trade 266 is: -4
The return for trade 267 is: 13
The return for trade 268 is: 8
The return for trade 269 is: 5
The return for trade 270 is: -2
The return for trade 271 is: 6
The return for trade 272 is: -3
The return for trade 273 is: 0
The return for trade 274 is: 1
The return for trade 275 is: -12
The return for trade 276 is: 32
The return for trade 277 is: 20
The return for trade 278 is: -2
The return for trade 279 is: -19
The return for trade 280 is: 63
The return for trade 281 is: -10
The return for trade 282 is: -18
The return for trade 283 is: 17
The return for trade 284 is: 1
The return for trade 285 is: -16
The return for trade 286 is: 5
The return for trade 287 is: 53
The return for trade 288 is: -10
The return for trade 289 is: -3
The return for trade 290 is: 2
The return for trade 291 is: 8
The return for trade 292 is: -8
The return for trade 293 is: -5
The return for trade 294 is: 4
The return for trade 295 is: 0
The return for trade 296 is: 17
The return for trade 297 is: -5
The return for trade 298 is: 7
The return for trade 299 is: 0
The return for trade 300 is: -4
The return for trade 301 is: 0
The return for trade 302 is: 93
The return for trade 303 is: 23
The return for trade 304 is: 0
The return for trade 305 is: -13
The return for trade 306 is: -8
The return for trade 307 is: 12
The return for trade 308 is: 3
The return for trade 309 is: 4
The return for trade 310 is: -1
The return for trade 311 is: 3
The return for trade 312 is: 1
The return for trade 313 is: -2
The return for trade 314 is: 5
The return for trade 315 is: -2
The return for trade 316 is: -10
The return for trade 317 is: -1
The return for trade 318 is: -7
The return for trade 319 is: -2
The return for trade 320 is: 4
The return for trade 321 is: 17
The return for trade 322 is: 29
The return for trade 323 is: -4
The return for trade 324 is: 13
The return for trade 325 is: -20
The return for trade 326 is: 42
The return for trade 327 is: 38
The return for trade 328 is: 1
The return for trade 329 is: 12
The return for trade 330 is: -8
The return for trade 331 is: -1
The return for trade 332 is: -7
The return for trade 333 is: -1
The return for trade 334 is: -3
The return for trade 335 is: 0
The return for trade 336 is: 1
The return for trade 337 is: 31
The return for trade 338 is: -1
The return for trade 339 is: 0
The return for trade 340 is: 3
The return for trade 341 is: -9
The return for trade 342 is: 27
The return for trade 343 is: 11
The return for trade 344 is: -9
The return for trade 345 is: 1
The return for trade 346 is: 21
The return for trade 347 is: 51
The return for trade 348 is: 83
The return for trade 349 is: -8
The return for trade 350 is: 0
The return for trade 351 is: -5
The return for trade 352 is: 4
The return for trade 353 is: -3
The return for trade 354 is: 18
The return for trade 355 is: 43
The return for trade 356 is: -7
The return for trade 357 is: 21
The return for trade 358 is: -9
The return for trade 359 is: -11
The return for trade 360 is: -5
The return for trade 361 is: 3
The return for trade 362 is: -8
The return for trade 363 is: 0
The return for trade 364 is: 19
The return for trade 365 is: -30
The return for trade 366 is: 23
The return for trade 367 is: -3
The return for trade 368 is: 22
The return for trade 369 is: 0
The return for trade 370 is: -4
The return for trade 371 is: 19
The return for trade 372 is: -9
The return for trade 373 is: -9
The return for trade 374 is: -1
The return for trade 375 is: 2
The return for trade 376 is: 10
The return for trade 377 is: -5
The return for trade 378 is: 27
The return for trade 379 is: 17
The return for trade 380 is: -6
The return for trade 381 is: 28
The return for trade 382 is: 26
The return for trade 383 is: 30
The return for trade 384 is: -23
The return for trade 385 is: -40
The return for trade 386 is: -4
The return for trade 387 is: 23
The return for trade 388 is: 20
The return for trade 389 is: 18
The return for trade 390 is: -11

IndexError: list index out of range

In [ ]:
# what happens with the positions while they're open, as well

returns = 0

# Gets the number of pips that the market moved during the day
df['difference (pips)'] = -(df['bidopen'] - df['askclose']) 
#df['p/l'] = df['difference'] * pip_cost * lot_size

# Calculates the daily return while a position is active
# 'Total' column records our running profit / loss for the strategy
for i, row in df.iterrows():
    if row['signal'] == 1:
        returns += (row['difference (pips)'] * pip_cost * lot_size)
        df.loc[i,'total'] = returns
    else:
        df.loc[i,'total'] = returns
        
#################don't actually understand the logic here: why do we calculate everyday p/l??  we are not trading every day.

In [ ]:

df.tail()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

fig = plt.figure(figsize=(24,16))
ax1 = fig.add_subplot(111,  ylabel='GBP/JPY')

# Plotting market prices and moving averages
df['askclose'].plot(ax=ax1, color='r', lw=1.)
df[['hma_fast', 'hma_slow']].plot(ax=ax1, lw=2.)

# Placing purple markers for position entry
ax1.plot(df.loc[df.position == 1.0].index, 
         df.hma_fast[df.position == 1.0],
         '^', markersize=5, color='m')

# Placing black markers for position exit
ax1.plot(df.loc[df.position == -1.0].index, 
         df.hma_slow[df.position == -1.0],
         'v', markersize=5, color='k')

# Plotting of returns
ax2 = ax1.twinx()
#ax2.grid(False)
ax2.set_ylabel('Profits in $')
ax2.plot(df['total'], color = 'green')

plt.show()

In [7]:
row

bidopen     26589.800000
bidclose    26579.100000
bidhigh     26589.900000
bidlow      26577.450000
askopen     26591.850000
askclose    26581.050000
askhigh     26592.700000
asklow      26580.000000
tickqty      1108.000000
hma_fast    26581.160926
hma_slow    26595.907327
signal          1.000000
position        0.000000
Name: 2018-10-01 00:00:00, dtype: float64